# Generated by Django 4.1.5 on 2023-12-06 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('job_category', models.CharField(max_length=200)),
                ('job_company', models.CharField(max_length=200)),
                ('job_experience', models.CharField(max_length=200)),
                ('job_salary', models.CharField(max_length=200)),
                ('job_qualification', models.CharField(max_length=200)),
                ('job_posted_on', models.DateTimeField(auto_now_add=True)),
                ('job_updated_on', models.DateTimeField(auto_now=True)),
                ('job_status', models.BooleanField(default=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['job_posted_on'],
            },
        ),
    ]
